# Generated by Django 4.1.7 on 2023-03-19 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_notificationstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstudent',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
