# Generated by Django 4.1.7 on 2023-03-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_alter_notificationstudent_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationStudent',
        ),
    ]
